version: '3'
services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL
      - RAILS_ENV
      - OB_CLIENT_ID
      - OB_CLIENT_SECRET
    depends_on:
      db:
        condition: service_healthy
      bootstrap:
        condition: service_completed_successfully
    command: [ "rails", "server", "-b", "0.0.0.0" ]

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - .:/usr/src/app
      - ./postgres-data:/var/lib/postgresql/data

  bootstrap:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URL
      - RAILS_ENV
      - OB_CLIENT_ID
      - OB_CLIENT_SECRET
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ./bootstrap_entrypoint
